#version: "3.5"

services:
  node-app:
    #build:
      #context: .
    image: 590272043641.dkr.ecr.eu-west-1.amazonaws.com/node-app:latest
    depends_on:
      - postgres-db
    restart: "always"
    container_name: akor-node-app
    environment:
      NODE_ENV: production 
      DB_HOST: "postgres-db"
      DB_USER: "akor"
      DB_PASS: "secret"
      DB_NAME: "demo" 
      DB_PORT: "5432"
      PORT: "5002"
    ports:
      - "8081:5002"
    volumes:
      - .:/www/app
    networks:
      - altsch-network

  postgres-db:
    image: postgres:17.2
    container_name: akor-postgres-db
    environment:
      POSTGRES_DB: "demo"
      POSTGRES_USER: "akor"
      POSTGRES_PASSWORD: "secret"
    networks:
      - altsch-network
    ports:
      - "5030:5432"

networks:
  altsch-network:
    driver: bridge
